# Generated by Django 6.0.2 on 2026-03-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_companytest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companytest',
            old_name='question',
            new_name='question_text',
        ),
    ]
